set nocompatible
syntax on
filetype plugin indent on
colo pure

set statusline=%<%f\ %h%w%m%r\ \ -\ %{g:colors_name}\ -\ %{FugitiveStatusline()}%=\ %-14.(%l,%c%V%)\ %P
set hlsearch incsearch autoindent smartindent smarttab termguicolors
set background=dark laststatus=2
set nu rnu ruler showcmd showmatch noswapfile autoread
set undofile
let &undodir=$HOME . "/.local/state/vim/undo/"
set mouse=nvi ttymouse=sgr nrformats-=octal formatoptions+=j foldopen-=block
set listchars=tab:>\ ,trail:-,nbsp:+,eol:$
set history=10000
set ttimeout splitbelow splitright

if has('win32')
    set guioptions-=t
    let &shell = executable('pwsh') ? 'pwsh' : 'powershell'
    let &shellcmdflag = "-NoLogo -NonInteractive -ExecutionPolicy RemoteSigned -Command [Console]::InputEncoding=[Console]::OutputEncoding=[System.Text.UTF8Encoding]::new();$PSDefaultParameterValues['Out-File:Encoding']='utf8';"
endif

runtime ftplugin/man.vim
packadd! matchit cfilter termdebug

nnoremap d_ d^
nnoremap c_ c^
inoremap , ,<C-g>u
inoremap . .<C-g>u
tnoremap <esc><esc> <C-\><C-n>
nnoremap Y y$
nnoremap J mzJ`z
vnoremap p "_dP
vnoremap < <gv
vnoremap > >gv
nnoremap - <cmd>Ex<cr>

autocmd! BufRead,BufNewFile *.typ set filetype=typst

let g:highlightedyank_highlight_duration = 200
let g:fzf_layout = { 'down': '40%' }

function! s:GetLanIp()
  if has('win32')
    let l:output = system('ipconfig')
    " Find IPv4 address starting with 192
    let l:lan_ip = matchstr(l:output, 'IPv4 Address[^:]*:\s*192\zs\(\.[0-9]\+\)\{3}')
    return '192' . l:lan_ip
  elseif has('mac')
    let l:cmd = 'ipconfig getifaddr en0'
    let l:ip = substitute(system(l:cmd), '\n\+$', '', '')
    return substitute(l:ip, '[[:cntrl:]]', '', 'g')
  elseif has('linux') || has('wsl')
    let l:cmd = "ip route get 1.1.1.1 | awk '{print $7}'"
    let l:ip = system(l:cmd)
    " Remove whitespace
    return substitute(l:ip, '[[:cntrl:][:space:]]', '', 'g')
  endif
endfunction

let g:mkdp_auto_close = 0
let g:mkdp_open_to_the_world = 1
let g:mkdp_open_ip = s:GetLanIp()
let g:mkdp_echo_preview_url = 1
let g:mkdp_port = "8085"
let g:mkdp_theme = "light"
