filetype plugin indent on
syntax on
hi Comment ctermfg=green guifg=green
set mouse=nvi nu rnu ruler showmatch noswapfile autoread undofile
set hlsearch incsearch
set colorcolumn=80 history=10000
let &undodir=$HOME . "/.local/state/vim/undo/"

runtime ftplugin/man.vim
packadd! matchit cfilter termdebug

nnoremap d_ d^
nnoremap c_ c^
inoremap , ,<C-g>u
inoremap . .<C-g>u
tnoremap <esc><esc> <C-\><C-n>
nnoremap Y y$
nnoremap J mzJ`z

autocmd! BufRead,BufNewFile *.typ set filetype=typst

" Highlight the 80th character if line is longer
function! HighlightEightiethChar()
    " Clear any existing matches
    call clearmatches()

    " Get all line numbers in the buffer
    let l:lines = range(1, line('$'))

    for l:line in l:lines
        " Get the content of the current line
        let l:content = getline(l:line)

        " If line is longer than 80 characters
        if len(l:content) >= 80
            " Match exactly the 80th character
            let l:pattern = '\%'.l:line.'l\%80v.'

            " Add a match with custom highlighting
            call matchadd('EightiethChar', l:pattern)
        endif
    endfor
endfunction

" Define custom highlight group
highlight EightiethChar ctermbg=red guibg=#592929

" Autocommand to run the highlighting function
augroup HighlightEightiethChar
    autocmd!
    " Run when entering a buffer, after reading a file, or after changes
    autocmd BufEnter,BufRead,TextChanged,InsertLeave * call HighlightEightiethChar()
augroup END

let data_dir = '~/.config/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    " Create required directories
    if !isdirectory(expand(data_dir . '/autoload'))
        call mkdir(expand(data_dir . '/autoload'), 'p')
    endif

    " Define the installation command based on OS
    let install_cmd = 'curl -fLo ' . expand(data_dir . '/autoload/plug.vim')
    \ . ' --create-dirs '
    \ . 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    " Execute the installation command
    echo "Installing vim-plug..."
    silent execute '!' . install_cmd

    " Check if installation was successful
    if v:shell_error == 0
        echo "vim-plug installed successfully!"
        " Automatically run PlugInstall for first time setup
        autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
    else
        echoerr "Failed to install vim-plug. Please check your internet
                    \ connection and try again."
    endif
endif

" Initialize plugin section
call plug#begin()
Plug 'https://github.com/junegunn/vim-easy-align'
Plug 'https://github.com/kaarmu/typst.vim'
Plug 'https://github.com/mbbill/undotree'
Plug 'https://github.com/sheerun/vim-polyglot'
Plug 'https://github.com/tommcdo/vim-exchange'
Plug 'https://github.com/tpope/vim-apathy'
Plug 'https://github.com/tpope/vim-commentary'
Plug 'https://github.com/tpope/vim-endwise'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'https://github.com/tpope/vim-rsi'
Plug 'https://github.com/tpope/vim-surround'
Plug 'https://github.com/tpope/vim-vinegar'
Plug 'https://github.com/wellle/targets.vim'
call plug#end()
