#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
# dbus-launch /usr/bin/startxfce4 &
dbus-launch startplasma-x11 &
# dbus-launch --exit-with-session gnome-session &
# dbus-launch i3 &
