-- require("luasnip.session.snippet_collection").clear_snippets = "c"
-- local ls = require("luasnip")
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local c = ls.choice_node
-- local fmt = require("luasnip.extras.fmt").fmt
--
-- local snippets = {}
--
-- return snippets
